### ISSUE TITLE
Can't get rid of helo-laravel...

### ISSUE THREAD

**Issue by ulfie22** [beyondcode/helo-laravel#10]
HELO works great for emails that my code sends - really awesome. Since I added it in the middle of a project, I didn't notice that it totally bombs out when using Laravel created authentication messages (see issue #1 ). I need to test some things that area, so I am trying to get past HELO. I changed my `.env` file back to my MailTrap settings, and the mail message I generate now go there, but the Laravel created emails still generate the 

```
Argument 1 passed to Illuminate\Notifications\Channels\MailChannel::__construct() must implement interface Illuminate\Contracts\Mail\Factory, instance of BeyondCode\HeloLaravel\Mailer given
``` 
error. Any idea how I can get around this?

Thanks!!

**Comment by sschlein** [comment]
It looks like you have installed the (this) optional helper package. You don't need it for using the HELO app. So if you remove it from your composer.json file and run `composer update` you should be good to go. 

So if you remove the helper package, you can use HELO again and shouldn't have any issues.

**Comment by ulfie22** [comment]
@sschlein Perfect - thanks!! Now I'm not clear why I installed this in the first place....
