### ISSUE TITLE
Debug information not populating when mail is sent through the queue

### ISSUE THREAD

**Issue by stephenhowells** [beyondcode/helo-laravel#14]
I have a basic mail method in a controller:

```php
Mail::to($request->user())
    ->queue(new SignedIn($data));
```

Helo does receive the message as expected but despite the optional package being installed, it doesn't send the debug information to Helo. I've tried using both sync and Horizon and neither will include debug information. The following code, skipping the queue, does send the debug information:

```php
Mail::to($request->user())
    ->send(new SignedIn($data));
```

**Comment by zupolgec** [comment]
See #5 and #12.

**Comment by stephenhowells** [comment]
@zupolgec Oops, okay closing the issue.
