### ISSUE TITLE
Issue when requiring package.

### ISSUE THREAD

**Issue by Erth0** [beyondcode/helo-laravel#15]
Getting this issue when installing this package or when requiring `therobfonz/laravel-mandrill-driver`
It seems like there is something wrong when this 2 need to be installed. Anyone else has come to this issue before?
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   BadMethodCallException 

  Method BeyondCode\HeloLaravel\Laravel7Mailer::extend does not exist.

  at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
     99|      */
    100|     public function __call($method, $parameters)
    101|     {
    102|         if (! static::hasMacro($method)) {
  > 103|             throw new BadMethodCallException(sprintf(
    104|                 'Method %s::%s does not exist.', static::class, $method
    105|             ));
    106|         }
    107|

      +9 vendor frames 
  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(LaravelMandrill\MandrillServiceProvider))

      +5 vendor frames 
  16  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by Erth0** [comment]
Actually it seems there is no conflict with `therobfonz/laravel-mandrill-driver` but something with helo package  at least on my app.

**Comment by szabizs** [comment]
I have the same issue.

**Comment by szabizs** [comment]
I've added this static function to `vendor\beyondcode\helo-laravel\src\Laravel7Mailer.php` and it solved my problem.

```
    /**
     * Void function, bug fix for BeyondCode Hello
     */
    public static function extend()
    {

    }
```

**Comment by Erth0** [comment]
Yeah i did this as well but the issue is when this will be update will be overridden. Probably the best way is to be fixed by Marcel.

**Comment by szabizs** [comment]
> Yeah i did this as well but the issue is when this will be update will be overridden. Probably the best way is to be fixed by Marcel.

True :)

**Comment by jongravois** [comment]
I have the same issue using PostmarkServiceProvider

**Comment by latwelve** [comment]
Trying to install laravel-postmark whilst Helo is installed and getting the same issue

**Comment by paperscissors** [comment]
Same, laravel postmark
