### ISSUE TITLE
built-in test command does not work

### ISSUE THREAD

**Issue by wmfairuz** [beyondcode/helo-laravel#2]
The built-in test command does not work. I didn't get any mail when doing "php artisan helo:test".

Instead I've tested using tinker the following and I receive the email in HELO.

```
Mail::send('welcome', [], function ($message) {
	$message->from('a@foo.com')->to('b@bar.com')->subject('test from tinkerwell');
});
```

**Comment by sschlein** [comment]
Which Laravel version are you using? I just tested it and it worked as intended

**Comment by wmfairuz** [comment]
I'm using Laravel 6.18.7

**Comment by sschlein** [comment]
Any errors? I tested on 6.2 and a fresh install and can't reproduce your issue

**Comment by wmfairuz** [comment]
No errors, just doesn't receive the email.

```
$ php artisan helo:test
Sending a test mail to HELO.
Check in HELO if it arrived!
```

Let me retest on a fresh install of L7. Will update soon

**Comment by wmfairuz** [comment]
No problem with L7. hmm.
