### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by repat** [beyondcode/helo-laravel#24]
Hi @mpociot ,

could you support PHP 8 please? :)

Unfortunately you also need to upgrade your dev dependencies (not a simple `| ^ 8.0`), but the test seems to work anyway:

![image](https://user-images.githubusercontent.com/516807/100586638-528a5900-3354-11eb-9082-012d14122e4f.png)

![image](https://user-images.githubusercontent.com/516807/100586534-2ec71300-3354-11eb-9a60-3955182b19d5.png)

Min versions to support PHP 8:
* 6.3.0: https://packagist.org/packages/orchestra/testbench#v6.3.0
* 9.3: https://packagist.org/packages/phpunit/phpunit#9.3.0

Thanks!

**Comment by repat** [comment]
@mpociot check out #25

**Comment by devingray** [comment]
@repat This is done and the issue can be closed :)

**Comment by repat** [comment]
thx!
