### ISSUE TITLE
Wrong package name in Laravel instruction

### ISSUE THREAD

**Issue by wmfairuz** [beyondcode/helo-laravel#3]
In HELO's settings, for Laravel, it mentions 

> To install the package use: composer require beyondcode/laravel-helo

It should be "composer require --dev beyondcode/helo-laravel" instead

**Comment by sschlein** [comment]
Whoops, I just fixed it and we'll likely release a 1.0.1 before we announce HELO later today. Thanks!

**Comment by sschlein** [comment]
For reference: https://github.com/beyondcode/helo-community/issues/1
