### ISSUE TITLE
Possible infinite loop detected in CreatesMailers trait

### ISSUE THREAD

**Issue by schonhoff** [beyondcode/helo-laravel#42]
Hello,

I'm sending out a mail to my user and after a short period of time I got a possible infinite loop detected by xdebug.

I tried sending out the test mail via `php artisan helo:test` and the response is 
```batch
Sending a test mail to HELO.
Check in HELO if it arrived!
```
And the mail arrived in HELO.
If I try to send a mail via the browser with 
```php
Route::get('test', function () {
    Mail::to('test@example.com)->send(new MyTestMail());
});
```
the infinite message is shown. Without XDebug active I will get a ERR_CONNECTION_RESET error. Here is the stacktrace:
![image](https://user-images.githubusercontent.com/42345405/235091338-792145d1-65e6-4b19-bb7e-0b463374c585.png)

If I change the line 71 in the CreatesMailers.php to be
```php
$symfonyTransport = $app['mailer']->getSymfonyTransport();
```
instead of
```php
$symfonyTransport = $app['mail.manager']->getSymfonyTransport();
```
the mail will be send to HELO. Because I don't know if this is a good change to make, I won't open a PR for this.

Maybe someone can look into this.

### Specs
Laravel Version: 10.9.0
BeyondCode HELO Version: 1.6.2.0 (Windows)
BeyondCode HELO Version Package: 1.6.1
Operating System: Windows 11
PHP Version: 8.2.4 / 8.1.9 / 8.1.18 (all have the same problem)
Xdebug Version: 3.2.0
Apache Version: 2.4.57.1 (WAMP)
Chrome Version: 112.0.5615.138

If more infos are needed, I will try to provide them.

### Others
I tried this in a fresh installed Laravel project, on a different computer (still Windows 11) and got the same result. 
On the 26th of April I could send mails without a problem to HELO but since yesterday I will get the error. I also tried different browsers (Chrome, Firefox, Edge) without success.
Edit: I tried `php artisan serve` as well with the same result.

**Comment by DougThwaites** [comment]
Thanks for the write up @schonhoff I am facing the same issue. 

With similar specs:

Laravel Version: 10.9.0
BeyondCode HELO Version: 1.6.2.0 (MacOS)
BeyondCode HELO Version Package: 1.6.1
PHP Version: 8.2.5

If I find anything more i'll update this issue.

**Comment by anand-patel** [comment]
I am also facing the same issue.

**Comment by antonioreyna** [comment]
same here

**Comment by octoxan** [comment]
Same issue here, completely dead in Laravel 10 because of this

**Comment by antonioreyna** [comment]
I hope they fixe this as its not a free service...

**Comment by mpociot** [comment]
This should now be fixed, thanks @octoxan
