### ISSUE TITLE
Helper package can't be installed when using laravels "global to address" feature.

### ISSUE THREAD

**Issue by eugen-stranz** [beyondcode/helo-laravel#43]
Hello there,

we just discovered a strange bug. 

Your composer package can't be installed if you use the "Global to address" [Feature of Laravel](https://laravel.com/docs/10.x/mail#using-a-global-to-address). 
```php
public function boot(): void
{
    if ($this->app->environment('local')) {
        Mail::alwaysTo('taylor@example.com');
    }
}
```

Once you remove those lines it works. We had this issue in our project and first we thaught that something else might trigger this behaviour.

But we went the extra mile and created a new laravel project with nothing in there - we added those lines into the AppServiceprovider and then we tried to install the helper package and it doesn't work.

You get the following error:

<img width="1920" alt="Screenshot 2023-06-17 at 7 44 24 PM" src="https://github.com/beyondcode/helo-laravel/assets/136219827/b31e3e7d-b600-4715-aac6-c650beecb51f">

**Comment by mechelon** [comment]
I could not reproduce this behaviour with Laravel 10 or 11. `Mail::alwaysTo` works as expected with HELO. Feel free to reopen if you can provide more information about this problem, e.g. a detailed `composer.json` file.
