### ISSUE TITLE
Queued Mailables – Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by heikokrebs** [beyondcode/helo-laravel#5]
When i use this package and try to queue a Mailable that implements ShouldQueue i get an Exception:

```
  Serialization of 'Closure' is not allowed

  at vendor/laravel/framework/src/Illuminate/Queue/Queue.php:147
    143| 
    144|         return array_merge($payload, [
    145|             'data' => [
    146|                 'commandName' => get_class($job),
    147|                 'command' => serialize(clone $job),
    148|             ],
    149|         ]);
    150|     }
    151| 
```

----------

Laravel version: 7.6.2
Laravel config cached: false
PHP version: 7.4.4

**Comment by romualdbrisson** [comment]
Same issue here...
PHP Version 7.3.
Thanks !

**Comment by joseaneto** [comment]
Same here with PHP 7.4

**Comment by pryley** [comment]
See also https://github.com/statamic/cms/issues/2262

**Comment by dniccum** [comment]
+1

**Comment by KevinBatdorf** [comment]
Came here to report the same. Using Statamic too (the test email utility)

**Comment by dorqa95** [comment]
Unfortunately is the same in laravel 8.36.0 and php 7.3.0 with queue.  Please take a look at this issue, thanks for your work!

**Comment by mpociot** [comment]
This is now fixed. And just as an FYI: you can use HELO without adding this helper package as well. You only loose some of the Laravel specific debug information - but the local mails are still going to work, as HELO is not Laravel specific.
