### ISSUE TITLE
Incompatible with Laravel Debugbar

### ISSUE THREAD

**Issue by stayallive** [beyondcode/helo-laravel#6]
I get the following 2 errors when having the [Laravel Debugbar](https://github.com/barryvdh/laravel-debugbar) active at the same time as this package.

```
Cannot add MailCollector to Laravel Debugbar: Method BeyondCode\HeloLaravel\Mailer::mailer does not exist.
/private/var/www/simulise/vendor/barryvdh/laravel-debugbar/src/LaravelDebugbar.php#427
```

```
Method BeyondCode\HeloLaravel\Mailer::mailer does not exist.
/private/var/www/simulise/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php#103
```

**Comment by tshafer** [comment]
I am running into the same issue.

**Comment by robclancy** [comment]
You could always use the better option that is clockwork. https://underground.works/clockwork/

**Comment by zupolgec** [comment]
@stayallive @tshafer can you please test v1.0.2 that fixed #1?

**Comment by stayallive** [comment]
Yes looks good on my end 👍

**Comment by tshafer** [comment]
Same, thanks!
