### ISSUE TITLE
incompatible with themsaid/laravel-mail-preview and jdavidbakr/mail-tracker and Qoraiche/laravel-mail-editor

### ISSUE THREAD

**Issue by vesper8** [beyondcode/helo-laravel#7]
I'm using these two packages in my application and after installing beyondcode/helo-laravel I am getting fatal errors everywhere:

```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   BadMethodCallException

  Method BeyondCode\HeloLaravel\Mailer::extend does not exist.

  at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
     99|      */
    100|     public function __call($method, $parameters)
    101|     {
    102|         if (! static::hasMacro($method)) {
  > 103|             throw new BadMethodCallException(sprintf(
    104|                 'Method %s::%s does not exist.', static::class, $method
    105|             ));
    106|         }
    107|

  • Bad Method Call: Did you mean BeyondCode\HeloLaravel\Mailer::send() ?

      +9 vendor frames
  10  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Themsaid\MailPreview\MailPreviewServiceProvider))

      +5 vendor frames
  16  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

and

```
 BadMethodCallException

  Method BeyondCode\HeloLaravel\Mailer::mailer does not exist.

  at vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:103
     99|      */
    100|     public function __call($method, $parameters)
    101|     {
    102|         if (! static::hasMacro($method)) {
  > 103|             throw new BadMethodCallException(sprintf(
    104|                 'Method %s::%s does not exist.', static::class, $method
    105|             ));
    106|         }
    107|

  • Bad Method Call: Did you mean BeyondCode\HeloLaravel\Mailer::failures() ?

      +17 vendor frames
  18  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(jdavidbakr\MailTracker\MailTrackerServiceProvider))

      +5 vendor frames
  24  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I get that I can completely replace themsaid/laravel-mail-preview with Helo, however jdavidbakr\MailTracker is something else and it provides a lot of value to my application as it tracks the opens/clicks of emails that are sent out. So I'd really like for it to be compatible with Helo.

I also get that it I can probably just not use this helper and then it will work. But if @mpociot knows how to make this plugin more friendly with other packages that would be great

**Comment by vesper8** [comment]
update: I also just found out it's causing a conflict with yet another mail-related package.. one that I use a lot to design my emails: https://github.com/Qoraiche/laravel-mail-editor

I get this error when trying to access the admin page that lets you previous and edit mailables in an editor

```
BadMethodCallException
Method BeyondCode\HeloLaravel\Mailer::mailer does not exist.
```

**Comment by zupolgec** [comment]
@vesper8 can you please test v1.0.2 that fixed #1?

**Comment by vesper8** [comment]
@zupolgec I was already using 1.0.2 when I filed this issue. Problem still exists

**Comment by zupolgec** [comment]
@vesper8 version 1.0.2 has been tagged after you posted this issue.

**Comment by vesper8** [comment]
oh my bad, I got confused with the version of the HELO desktop app which has been a 1.0.2 since it first released I think.

I just tested all incompatibilities mentioned above and indeed the 1.0.2 version of this package has resolved all conflicts except for the one with themsaid/laravel-mail-preview.
